### ISSUE TITLE
CentOS 7 versions of cvmfs-*

### ISSUE THREAD

**Issue by kreczko** [hepsw/docks#22]
Since some experiments are slowly moving towards CentOS 7, I wanted to ask if there any plans to add C7 versions of the `cvmfs-*` images.

If there are none, I can have a look. It seems to me that there are no obvious roadblocks for that.
Any particular wishes as to folder names? E.g. `cvmfs-base-centos7`, `-c7`, etc?

**Comment by sbinet** [comment]
(apologies for the belated answer, dotGo conference :))

yes, sounds good.
